version: '3'

services:
  db:
    image: postgres:13
    container_name: default_rails_app_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  web:
    build: .
    image: default_rails_app/web:latest
    container_name: default_rails_app_web
    command: bash -c "/app/scripts/run_puma.sh"
    depends_on:
      - db
    volumes:
      - ./:/app
      - /app/tmp
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
    ports:
      - 8080:8080
    environment:
      CREATE_DB_ON_INIT: 'true'